### ISSUE TITLE
ใส่ GitHub Webhook ใน Discord

### ISSUE THREAD

**Issue by LagSeeN** [creatorsgarten/kaogeek-discord-bot#103]
### Discussed in https://github.com/creatorsgarten/kaogeek-discord-bot/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **beam41** May 17, 2023</sup>
จะได้ติดตามง่ายๆเวลามี activity อะไรบน github
https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22</div>

**Comment by LagSeeN** [comment]
ใครจะทำเดียวส่ง webhook ไปให้

**Comment by dtinth** [comment]
added krub
