### ISSUE TITLE
add Vitest to project to allow unit testing some logic

### ISSUE THREAD

**Issue by dtinth** [creatorsgarten/kaogeek-discord-bot#42]
### Overview

add Vitest to project to allow unit testing some logic

- add Vitest to project
- add a dummy test to verify that Vitest is working, e.g. `expect('foo').toBe('foo')`
- add a CI configuration to run Vitest

### Why you want this feature?

there are some complex logic, e.g. emoji detection #36. maybe these logic can have automated tests to increase confidence in the system

(please comment if you would like to help, so other people know someone is already working on it)

**Comment by samithiwat** [comment]
I would do krubb
