### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by Leomotors** [creatorsgarten/kaogeek-discord-bot#85]
According to https://github.com/creatorsgarten/kaogeek-discord-bot/pull/84#issuecomment-1555000954

It's weird that `.DS_Store` is not there in `.gitignore` template 😂 

## To add to `.gitignore`
- `.DS_Store` and `__MACOSX`
- `package-lock.json` because someone insists to use `npm` (We already have `yarn.lock` in `.gitignore`, so group them together will be very nice)

**Comment by ujwalkumar1995** [comment]
Hey @Leomotors 
I would like to work on this. Could you please assign this to me?

**Comment by Leomotors** [comment]
> Hey @Leomotors I would like to work on this. Could you please assign this to me?

@ujwalkumar1995 👍🙏
