### ISSUE TITLE
[FEATURE] Reassign "flag" role for rejoining users.

### ISSUE THREAD

**Issue by buskun** [creatorsgarten/kaogeek-discord-bot#93]
### Overview

Proposed steps:
1. When user is flagged, we save those user to flag table in db
2. If user is rejoin, we check against the flag table and reapply the role

* When user is unflagged, remove those user from flag table 

### Why you want this feature?

**\*This is just a quick fix for current issue***

Currently, there are some flagged users making themselves unflagged by leaving the server and rejoining.
Admins suggest that, we should reapply flag role to those who leave with the role.

**Comment by samithiwat** [comment]
I can krub, can you please assign this ticket to me

**Comment by samithiwat** [comment]
closed use Wick Quarantine
